version: '3'

services: 
  web-service:
    build: ./web-service
    volumes: 
      - ./web-service:/app
    ports:
      - 5001:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379