version: '3'

services: 
  web-service:
    build: ./web-service
    volumes: 
      - C:/Users/1022772/Documents/Work/ExploreBhavCopy\web-service:/app_data
      # - /web-service:/app_data
    ports:
      - 5001:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379