version: '3'

services: 
  web-service:
    build: ./web-service
    volumes: 
      - C:/Users/1022772/Documents/Work/ExploreBhavCopy/web-service:/app_data
    #   - /web-service:/app_data
    ports:
      - 80:80
    depends_on:
      - redis
    networks:
      - network_1

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - network_1
networks:
  network_1: